server:
  port: 8000
spring:
  application:
    name: produto-service
  datasource:
    url: jdbc:postgresql://localhost/produto_db
    username: postgres
    password: 2403
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    locations:
    - classpath:/db_migration
